name: order_analysis
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.*
  - numpy=1.26.*
  - matplotlib=3.8.*
  - seaborn=0.13.*
  - scikit-learn=1.4.*
  - requests=2.31.*
  - jupyter=1.0.*
  - openpyxl=3.1.*
  - pip=24.*
  - pip:
      - black==24.4.*
